<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('countries')->insert([
            ['country_name' => 'Afghanistan', 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani', 'currency_sign' => '؋', 'countrycode' => 'AF', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Albania', 'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek', 'currency_sign' => 'L', 'countrycode' => 'AL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Algeria', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'currency_sign' => 'د.ج', 'countrycode' => 'DZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Andorra', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'AD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Angola', 'currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza', 'currency_sign' => 'Kz', 'countrycode' => 'AO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Antigua and Barbuda', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'AG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Argentina', 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'currency_sign' => '$', 'countrycode' => 'AR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Armenia', 'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram', 'currency_sign' => 'դր.', 'countrycode' => 'AM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Australia', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_sign' => '$', 'countrycode' => 'AU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Austria', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'AT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Azerbaijan', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat', 'currency_sign' => '₼', 'countrycode' => 'AZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bahamas', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'currency_sign' => '$', 'countrycode' => 'BS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bahrain', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'currency_sign' => '.د.ب', 'countrycode' => 'BH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bangladesh', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka', 'currency_sign' => '৳', 'countrycode' => 'BD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Barbados', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian Dollar', 'currency_sign' => '$', 'countrycode' => 'BB', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belarus', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble', 'currency_sign' => 'Br', 'countrycode' => 'BY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belgium', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'BE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belize', 'currency_code' => 'BZD', 'currency_name' => 'Belize Dollar', 'currency_sign' => '$', 'countrycode' => 'BZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Benin', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'BJ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bhutan', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'currency_sign' => '₹', 'countrycode' => 'BT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bolivia', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano', 'currency_sign' => 'Bs', 'countrycode' => 'BO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark', 'currency_sign' => 'KM', 'countrycode' => 'BA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Botswana', 'currency_code' => 'BWP', 'currency_name' => 'Botswana Pula', 'currency_sign' => 'P', 'countrycode' => 'BW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Brazil', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'currency_sign' => 'R$', 'countrycode' => 'BR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Brunei', 'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar', 'currency_sign' => '$', 'countrycode' => 'BN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bulgaria', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev', 'currency_sign' => 'лв', 'countrycode' => 'BG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Burkina Faso', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'BF', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Burundi', 'currency_code' => 'BIF', 'currency_name' => 'Burundian Franc', 'currency_sign' => 'Fr', 'countrycode' => 'BI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cabo Verde', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean Escudo', 'currency_sign' => '$', 'countrycode' => 'CV', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cambodia', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel', 'currency_sign' => '៛', 'countrycode' => 'KH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cameroon', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'CM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Canada', 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'currency_sign' => '$', 'countrycode' => 'CA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Central African Republic', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'CF', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Chad', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'TD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Chile', 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'currency_sign' => '$', 'countrycode' => 'CL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'China', 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan', 'currency_sign' => '¥', 'countrycode' => 'CN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Colombia', 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'currency_sign' => '$', 'countrycode' => 'CO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Comoros', 'currency_code' => 'KMF', 'currency_name' => 'Comorian Franc', 'currency_sign' => 'Fr', 'countrycode' => 'KM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Congo (Congo-Brazzaville)', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'CG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Costa Rica', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón', 'currency_sign' => '₡', 'countrycode' => 'CR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Croatia', 'currency_code' => 'HRK', 'currency_name' => 'Croatian Kuna', 'currency_sign' => 'kn', 'countrycode' => 'HR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cuba', 'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso', 'currency_sign' => '$', 'countrycode' => 'CU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cyprus', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'CY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Czechia (Czech Republic)', 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna', 'currency_sign' => 'Kč', 'countrycode' => 'CZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Denmark', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_sign' => 'kr', 'countrycode' => 'DK', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Djibouti', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc', 'currency_sign' => 'Fr', 'countrycode' => 'DJ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Dominica', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'DM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Dominican Republic', 'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso', 'currency_sign' => '$', 'countrycode' => 'DO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ecuador', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'EC', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Egypt', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'currency_sign' => 'ج.م', 'countrycode' => 'EG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'El Salvador', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'SV', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Equatorial Guinea', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'GQ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Eritrea', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean Nakfa', 'currency_sign' => 'Nfk', 'countrycode' => 'ER', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Estonia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'EE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Eswatini (fmr. "Swaziland")', 'currency_code' => 'SZL', 'currency_name' => 'Swazi Lilangeni', 'currency_sign' => 'E', 'countrycode' => 'SZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ethiopia', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'currency_sign' => 'Br', 'countrycode' => 'ET', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Fiji', 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar', 'currency_sign' => '$', 'countrycode' => 'FJ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Finland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'FI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'France', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'FR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Gabon', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'GA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Gambia', 'currency_code' => 'GMD', 'currency_name' => 'Gambian Dalasi', 'currency_sign' => 'D', 'countrycode' => 'GM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Georgia', 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari', 'currency_sign' => '₾', 'countrycode' => 'GE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Germany', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'DE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ghana', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi', 'currency_sign' => '₵', 'countrycode' => 'GH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Greece', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'GR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Grenada', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'GD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guatemala', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal', 'currency_sign' => 'Q', 'countrycode' => 'GT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guinea', 'currency_code' => 'GNF', 'currency_name' => 'Guinean Franc', 'currency_sign' => 'Fr', 'countrycode' => 'GN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guinea-Bissau', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'GW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guyana', 'currency_code' => 'GYD', 'currency_name' => 'Guyanese Dollar', 'currency_sign' => '$', 'countrycode' => 'GY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Haiti', 'currency_code' => 'HTG', 'currency_name' => 'Haitian Gourde', 'currency_sign' => 'G', 'countrycode' => 'HT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Honduras', 'currency_code' => 'HNL', 'currency_name' => 'Honduran Lempira', 'currency_sign' => 'L', 'countrycode' => 'HN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Hungary', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint', 'currency_sign' => 'Ft', 'countrycode' => 'HU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iceland', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna', 'currency_sign' => 'kr', 'countrycode' => 'IS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'India', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'currency_sign' => '₹', 'countrycode' => 'IN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Indonesia', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'currency_sign' => 'Rp', 'countrycode' => 'ID', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iran', 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'currency_sign' => '﷼', 'countrycode' => 'IR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iraq', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'currency_sign' => 'ع.د', 'countrycode' => 'IQ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ireland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'IE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Israel', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel', 'currency_sign' => '₪', 'countrycode' => 'IL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Italy', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'IT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Jamaica', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar', 'currency_sign' => '$', 'countrycode' => 'JM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Japan', 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen', 'currency_sign' => '¥', 'countrycode' => 'JP', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Jordan', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'currency_sign' => 'د.ا', 'countrycode' => 'JO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kazakhstan', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge', 'currency_sign' => '〒', 'countrycode' => 'KZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kenya', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'currency_sign' => 'KSh', 'countrycode' => 'KE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kiribati', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_sign' => '$', 'countrycode' => 'KI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Korea (North)', 'currency_code' => 'KPW', 'currency_name' => 'North Korean Won', 'currency_sign' => '₩', 'countrycode' => 'KP', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Korea (South)', 'currency_code' => 'KRW', 'currency_name' => 'South Korean Won', 'currency_sign' => '₩', 'countrycode' => 'KR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kuwait', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'currency_sign' => 'د.ك', 'countrycode' => 'KW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kyrgyzstan', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani Som', 'currency_sign' => 'с', 'countrycode' => 'KG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Laos', 'currency_code' => 'LAK', 'currency_name' => 'Laotian Kip', 'currency_sign' => '₭', 'countrycode' => 'LA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Latvia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'LV', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lebanon', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'currency_sign' => 'ل.ل', 'countrycode' => 'LB', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lesotho', 'currency_code' => 'LSL', 'currency_name' => 'Lesotho Loti', 'currency_sign' => 'L', 'countrycode' => 'LS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Liberia', 'currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar', 'currency_sign' => '$', 'countrycode' => 'LR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Libya', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar', 'currency_sign' => 'ل.د', 'countrycode' => 'LY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Liechtenstein', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_sign' => 'Fr', 'countrycode' => 'LI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lithuania', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'LT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Luxembourg', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'LU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Madagascar', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary', 'currency_sign' => 'Ar', 'countrycode' => 'MG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malawi', 'currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha', 'currency_sign' => 'MK', 'countrycode' => 'MW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malaysia', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit', 'currency_sign' => 'RM', 'countrycode' => 'MY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Maldives', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa', 'currency_sign' => 'Rf', 'countrycode' => 'MV', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mali', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'ML', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malta', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'MT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Marshall Islands', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'MH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mauritania', 'currency_code' => 'MRU', 'currency_name' => 'Mauritanian Ouguiya', 'currency_sign' => 'UM', 'countrycode' => 'MR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mauritius', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee', 'currency_sign' => '₨', 'countrycode' => 'MU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mexico', 'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso', 'currency_sign' => '$', 'countrycode' => 'MX', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Micronesia', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'FM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Moldova', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu', 'currency_sign' => 'L', 'countrycode' => 'MD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Monaco', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'MC', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mongolia', 'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tugrik', 'currency_sign' => '₮', 'countrycode' => 'MN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Montenegro', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'ME', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Morocco', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'currency_sign' => 'د.م.', 'countrycode' => 'MA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mozambique', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical', 'currency_sign' => 'MT', 'countrycode' => 'MZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Myanmar (formerly Burma)', 'currency_code' => 'MMK', 'currency_name' => 'Burmese Kyat', 'currency_sign' => 'Ks', 'countrycode' => 'MM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Namibia', 'currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar', 'currency_sign' => '$', 'countrycode' => 'NA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nauru', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_sign' => '$', 'countrycode' => 'NR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nepal', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'currency_sign' => 'Rs', 'countrycode' => 'NP', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Netherlands', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'NL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'New Zealand', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_sign' => '$', 'countrycode' => 'NZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nicaragua', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan Córdoba', 'currency_sign' => 'C$', 'countrycode' => 'NI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Niger', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'NE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nigeria', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira', 'currency_sign' => '₦', 'countrycode' => 'NG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'North Macedonia', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar', 'currency_sign' => 'ден', 'countrycode' => 'MK', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Norway', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'currency_sign' => 'kr', 'countrycode' => 'NO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Oman', 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial', 'currency_sign' => 'ر.ع.', 'countrycode' => 'OM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Pakistan', 'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee', 'currency_sign' => '₨', 'countrycode' => 'PK', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Palau', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'PW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Panama', 'currency_code' => 'PAB', 'currency_name' => 'Panamanian Balboa', 'currency_sign' => 'B/.', 'countrycode' => 'PA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Papua New Guinea', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina', 'currency_sign' => 'K', 'countrycode' => 'PG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Paraguay', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan Guarani', 'currency_sign' => '₲', 'countrycode' => 'PY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Peru', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Nuevo Sol', 'currency_sign' => 'S/', 'countrycode' => 'PE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Philippines', 'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso', 'currency_sign' => '₱', 'countrycode' => 'PH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Poland', 'currency_code' => 'PLN', 'currency_name' => 'Polish Zloty', 'currency_sign' => 'zł', 'countrycode' => 'PL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Portugal', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'PT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Qatar', 'currency_code' => 'QAR', 'currency_name' => 'Qatari Rial', 'currency_sign' => 'ر.ق', 'countrycode' => 'QA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Romania', 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu', 'currency_sign' => 'lei', 'countrycode' => 'RO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Russia', 'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble', 'currency_sign' => '₽', 'countrycode' => 'RU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Rwanda', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan Franc', 'currency_sign' => 'Fr', 'countrycode' => 'RW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Kitts and Nevis', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'KN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Lucia', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'LC', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Vincent and the Grenadines', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'currency_sign' => '$', 'countrycode' => 'VC', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Samoa', 'currency_code' => 'WST', 'currency_name' => 'Samoan Tala', 'currency_sign' => 'T', 'countrycode' => 'WS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'San Marino', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'SM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sao Tome and Principe', 'currency_code' => 'STN', 'currency_name' => 'São Tomé and Príncipe Dobra', 'currency_sign' => 'Db', 'countrycode' => 'ST', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saudi Arabia', 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal', 'currency_sign' => 'ر.س', 'countrycode' => 'SA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Senegal', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'SN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Serbia', 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar', 'currency_sign' => 'дин', 'countrycode' => 'RS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Seychelles', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee', 'currency_sign' => 'SRe', 'countrycode' => 'SC', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sierra Leone', 'currency_code' => 'SLL', 'currency_name' => 'Sierra Leonean Leone', 'currency_sign' => 'Le', 'countrycode' => 'SL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Singapore', 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'currency_sign' => '$', 'countrycode' => 'SG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sint Maarten', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillean Guilder', 'currency_sign' => 'ƒ', 'countrycode' => 'SX', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Slovakia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'SK', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Slovenia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'SI', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Solomon Islands', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar', 'currency_sign' => '$', 'countrycode' => 'SB', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Somalia', 'currency_code' => 'SOS', 'currency_name' => 'Somali Shilling', 'currency_sign' => 'Sh', 'countrycode' => 'SO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'South Africa', 'currency_code' => 'ZAR', 'currency_name' => 'South African Rand', 'currency_sign' => 'R', 'countrycode' => 'ZA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'South Sudan', 'currency_code' => 'SSP', 'currency_name' => 'South Sudanese Pound', 'currency_sign' => '£', 'countrycode' => 'SS', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Spain', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'ES', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sri Lanka', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee', 'currency_sign' => 'Rs', 'countrycode' => 'LK', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sudan', 'currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound', 'currency_sign' => 'ج.س.', 'countrycode' => 'SD', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Suriname', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese Dollar', 'currency_sign' => '$', 'countrycode' => 'SR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sweden', 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona', 'currency_sign' => 'kr', 'countrycode' => 'SE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Switzerland', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_sign' => 'Fr', 'countrycode' => 'CH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Syria', 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'currency_sign' => 'ل.س', 'countrycode' => 'SY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Taiwan', 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar', 'currency_sign' => 'NT$', 'countrycode' => 'TW', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tajikistan', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni', 'currency_sign' => 'SM', 'countrycode' => 'TJ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tanzania', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling', 'currency_sign' => 'TSh', 'countrycode' => 'TZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Thailand', 'currency_code' => 'THB', 'currency_name' => 'Thai Baht', 'currency_sign' => '฿', 'countrycode' => 'TH', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Timor-Leste', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'TL', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Togo', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'currency_sign' => 'Fr', 'countrycode' => 'TG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tonga', 'currency_code' => 'TOP', 'currency_name' => 'Tongan Paʻanga', 'currency_sign' => 'T$', 'countrycode' => 'TO', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Trinidad and Tobago', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar', 'currency_sign' => 'TT$', 'countrycode' => 'TT', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tunisia', 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar', 'currency_sign' => 'د.ت', 'countrycode' => 'TN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Turkey', 'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira', 'currency_sign' => '₺', 'countrycode' => 'TR', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Turkmenistan', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistani Manat', 'currency_sign' => 'T', 'countrycode' => 'TM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tuvalu', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_sign' => '$', 'countrycode' => 'TV', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uganda', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling', 'currency_sign' => 'UGX', 'countrycode' => 'UG', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ukraine', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia', 'currency_sign' => '₴', 'countrycode' => 'UA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United Arab Emirates', 'currency_code' => 'AED', 'currency_name' => 'United Arab Emirates Dirham', 'currency_sign' => 'د.إ', 'countrycode' => 'AE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United Kingdom', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_sign' => '£', 'countrycode' => 'GB', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United States', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_sign' => '$', 'countrycode' => 'US', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uruguay', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso', 'currency_sign' => '$U', 'countrycode' => 'UY', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uzbekistan', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani Som', 'currency_sign' => 'soʻm', 'countrycode' => 'UZ', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vanuatu', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu', 'currency_sign' => 'Vt', 'countrycode' => 'VU', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vatican City', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_sign' => '€', 'countrycode' => 'VA', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Venezuela', 'currency_code' => 'VES', 'currency_name' => 'Venezuelan Bolívar', 'currency_sign' => 'Bs.S.', 'countrycode' => 'VE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vietnam', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong', 'currency_sign' => '₫', 'countrycode' => 'VN', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Yemen', 'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial', 'currency_sign' => 'ر.ي', 'countrycode' => 'YE', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Zambia', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha', 'currency_sign' => 'ZK', 'countrycode' => 'ZM', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Zimbabwe', 'currency_code' => 'ZWL', 'currency_name' => 'Zimbabwean Dollar', 'currency_sign' => 'Z$', 'countrycode' => 'ZW', 'created_at' => now(), 'updated_at' => now()],
        ]);    
    }
}
